BOOTLOADER = atmel-dfu
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = yes
DEBUG_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MOUSEKEY_ENABLE =  no
WPM_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = yes

SRC += oled.c
